### ISSUE TITLE
Odd errors when trying to play sound

### ISSUE THREAD

**Issue by rememberlenny** [mike-bourgeous/mb-sound#18]
When trying to do the plot method inside the bin/sound.rb prompt, I was getting an spawn error that I've never seen in a ruby command.

```
Plotting "sounds/sine/sine_100_1s_mono.flac"

Errno::ENOENT: No such file or directory - fork failed
from /Users/leonardbogdonoff/Spaceship/milk-video/milk-spaceship/milk-audio-wave/mb-sound/vendor/bundle/ruby/3.0.0/bundler/gems/mb-math-e182bca71f4e/lib/mb/m/plot.rb:56:in `spawn'
```

I love what you are working on and would love to help debug this.

Happy to help via email or phone. lenny@milkvideo.com

Big thanks!

**Comment by mike-bourgeous** [comment]
Thanks for reporting this, and sorry I missed this issue until now.  Did you install gnuplot using Brew (`brew install gnuplot --with-x11`)?  If so I can add macOS instructions to the README to help with this, and try to detect and report spawn failures.
